### ISSUE TITLE
Interaction only mode

### ISSUE THREAD

**Issue by atymic** [Astrian/cfturnstile-vue3#5]
Can we get an option to set `appearance` to `interaction-only`?

**Comment by Astrian** [comment]
> Can we get an option to set `appearance` to `interaction-only`?

Any document reference available?

**Comment by Astrian** [comment]
> https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#configurations

I have already added it to #6 with full parameter configuration support. If there are any new bugs or problems, feel free to raise a new issue.
